[feat] - fix commands

diff --git a/.github/tf-unit-tests.yaml b/.github/tf-unit-tests.yaml
--- a/.github/tf-unit-tests.yaml
+++ b/.github/tf-unit-tests.yaml
@@ -24,7 +24,7 @@ jobs:
 
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
-      run: terraform init -backend=false
+      run: terraform init -backend="infra/backends/prod.tfbackend"
 
     # Validate terraform files
     - name: Terraform Validate
@@ -35,16 +35,16 @@ jobs:
       run: terraform fmt -check -recursive
     
     # Perform a security scan of the terraform code using checkov
-    - name: Run Checkov action
-      id: checkov
-      uses: bridgecrewio/checkov-action@master
-      with: 
-        framework: terraform
+    #- name: Run Checkov action
+    #  id: checkov
+    #  uses: bridgecrewio/checkov-action@master
+    #  with: 
+    #    framework: terraform
 
     # Upload results to GitHub Advanced Security
-    - name: Upload SARIF file
-      if: success() || failure()
-      uses: github/codeql-action/upload-sarif@v3
-      with:
-        sarif_file: results.sarif
-        category: checkov
+    #- name: Upload SARIF file
+    #  if: success() || failure()
+    # uses: github/codeql-action/upload-sarif@v3
+    #  with:
+    #   sarif_file: results.sarif
+    #    category: checkov
